# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/lmats012/Pokemon_Battle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/lmats012/Pokemon_Battle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/lmats012/Pokemon_Battle/CMakeFiles /home/csmajs/lmats012/Pokemon_Battle//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/lmats012/Pokemon_Battle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testBalls

# Build rule for target.
testBalls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testBalls
.PHONY : testBalls

# fast build rule for target.
testBalls/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/build
.PHONY : testBalls/fast

src/Item.o: src/Item.cpp.o
.PHONY : src/Item.o

# target to build an object file
src/Item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Item.cpp.o
.PHONY : src/Item.cpp.o

src/Item.i: src/Item.cpp.i
.PHONY : src/Item.i

# target to preprocess a source file
src/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Item.cpp.i
.PHONY : src/Item.cpp.i

src/Item.s: src/Item.cpp.s
.PHONY : src/Item.s

# target to generate assembly for a file
src/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Item.cpp.s
.PHONY : src/Item.cpp.s

src/Pokeballs/GreatBall.o: src/Pokeballs/GreatBall.cpp.o
.PHONY : src/Pokeballs/GreatBall.o

# target to build an object file
src/Pokeballs/GreatBall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Pokeballs/GreatBall.cpp.o
.PHONY : src/Pokeballs/GreatBall.cpp.o

src/Pokeballs/GreatBall.i: src/Pokeballs/GreatBall.cpp.i
.PHONY : src/Pokeballs/GreatBall.i

# target to preprocess a source file
src/Pokeballs/GreatBall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Pokeballs/GreatBall.cpp.i
.PHONY : src/Pokeballs/GreatBall.cpp.i

src/Pokeballs/GreatBall.s: src/Pokeballs/GreatBall.cpp.s
.PHONY : src/Pokeballs/GreatBall.s

# target to generate assembly for a file
src/Pokeballs/GreatBall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Pokeballs/GreatBall.cpp.s
.PHONY : src/Pokeballs/GreatBall.cpp.s

src/Pokeballs/Pokeball.o: src/Pokeballs/Pokeball.cpp.o
.PHONY : src/Pokeballs/Pokeball.o

# target to build an object file
src/Pokeballs/Pokeball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Pokeballs/Pokeball.cpp.o
.PHONY : src/Pokeballs/Pokeball.cpp.o

src/Pokeballs/Pokeball.i: src/Pokeballs/Pokeball.cpp.i
.PHONY : src/Pokeballs/Pokeball.i

# target to preprocess a source file
src/Pokeballs/Pokeball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Pokeballs/Pokeball.cpp.i
.PHONY : src/Pokeballs/Pokeball.cpp.i

src/Pokeballs/Pokeball.s: src/Pokeballs/Pokeball.cpp.s
.PHONY : src/Pokeballs/Pokeball.s

# target to generate assembly for a file
src/Pokeballs/Pokeball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Pokeballs/Pokeball.cpp.s
.PHONY : src/Pokeballs/Pokeball.cpp.s

src/Pokeballs/StandardBall.o: src/Pokeballs/StandardBall.cpp.o
.PHONY : src/Pokeballs/StandardBall.o

# target to build an object file
src/Pokeballs/StandardBall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Pokeballs/StandardBall.cpp.o
.PHONY : src/Pokeballs/StandardBall.cpp.o

src/Pokeballs/StandardBall.i: src/Pokeballs/StandardBall.cpp.i
.PHONY : src/Pokeballs/StandardBall.i

# target to preprocess a source file
src/Pokeballs/StandardBall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Pokeballs/StandardBall.cpp.i
.PHONY : src/Pokeballs/StandardBall.cpp.i

src/Pokeballs/StandardBall.s: src/Pokeballs/StandardBall.cpp.s
.PHONY : src/Pokeballs/StandardBall.s

# target to generate assembly for a file
src/Pokeballs/StandardBall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Pokeballs/StandardBall.cpp.s
.PHONY : src/Pokeballs/StandardBall.cpp.s

src/Pokeballs/UltraBall.o: src/Pokeballs/UltraBall.cpp.o
.PHONY : src/Pokeballs/UltraBall.o

# target to build an object file
src/Pokeballs/UltraBall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Pokeballs/UltraBall.cpp.o
.PHONY : src/Pokeballs/UltraBall.cpp.o

src/Pokeballs/UltraBall.i: src/Pokeballs/UltraBall.cpp.i
.PHONY : src/Pokeballs/UltraBall.i

# target to preprocess a source file
src/Pokeballs/UltraBall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Pokeballs/UltraBall.cpp.i
.PHONY : src/Pokeballs/UltraBall.cpp.i

src/Pokeballs/UltraBall.s: src/Pokeballs/UltraBall.cpp.s
.PHONY : src/Pokeballs/UltraBall.s

# target to generate assembly for a file
src/Pokeballs/UltraBall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/Pokeballs/UltraBall.cpp.s
.PHONY : src/Pokeballs/UltraBall.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testBalls.dir/build.make CMakeFiles/testBalls.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... testBalls"
	@echo "... src/Item.o"
	@echo "... src/Item.i"
	@echo "... src/Item.s"
	@echo "... src/Pokeballs/GreatBall.o"
	@echo "... src/Pokeballs/GreatBall.i"
	@echo "... src/Pokeballs/GreatBall.s"
	@echo "... src/Pokeballs/Pokeball.o"
	@echo "... src/Pokeballs/Pokeball.i"
	@echo "... src/Pokeballs/Pokeball.s"
	@echo "... src/Pokeballs/StandardBall.o"
	@echo "... src/Pokeballs/StandardBall.i"
	@echo "... src/Pokeballs/StandardBall.s"
	@echo "... src/Pokeballs/UltraBall.o"
	@echo "... src/Pokeballs/UltraBall.i"
	@echo "... src/Pokeballs/UltraBall.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

